name: Autodeploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Delete gh-pages branch from remote
      run: |
        git push origin --delete gh-pages || true

    - name: Create new gh-pages branch
      run: |
        git checkout --orphan gh-pages

    - name: Add all files to gh-pages
      run: |
        git add --all
        git commit -m "Deploy to gh-pages"

    - name: Push to gh-pages branch
      run: |
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}